# docker-compose.yml
# Coolify deployment - Supabase entegreli
# PostgreSQL: Mevcut Supabase kullanılıyor
# Portlar: Çakışmalar çözüldü

services:
  redis:
    container_name: airweave-redis
    image: redis:7-alpine
    ports:
      - "6380:6379"  # Port değiştirildi (6379 -> 6380)
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure

  backend:
    container_name: airweave-backend
    image: ${BACKEND_IMAGE:-ghcr.io/airweave-ai/airweave-backend:latest}
    ports:
      - "8001:8001"
    environment:
      # Supabase PostgreSQL Bağlantısı
      - POSTGRES_HOST=supabase-db-d0cso0goco0swwcgc4gkgw8c
      - POSTGRES_PORT=5432
      - POSTGRES_USER=supabase_admin
      - POSTGRES_PASSWORD=PZQEkh2IrpL2CIo00gyuOzqdqnEwMT5I
      - POSTGRES_DB=postgres
      - DATABASE_URL=postgresql://supabase_admin:PZQEkh2IrpL2CIo00gyuOzqdqnEwMT5I@supabase-db-d0cso0goco0swwcgc4gkgw8c:5432/postgres
      
      # Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      
      # Qdrant - Mevcut Qdrant kullanılıyor
      - QDRANT_HOST=qdrant-ik4c0s48cwco4occo4kw8okg
      - QDRANT_PORT=6333
      - QDRANT_URL=http://qdrant-ik4c0s48cwco4occo4kw8okg:6333
      
      # Text2Vec
      - TEXT2VEC_INFERENCE_URL=http://text2vec-transformers:8080
      
      # Environment
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - LOCAL_DEVELOPMENT=false
      
      # Temporal
      - TEMPORAL_HOST=temporal
      - TEMPORAL_PORT=7233
      - TEMPORAL_NAMESPACE=default
      - TEMPORAL_ENABLED=true
      
      # Auth
      - AUTH_ENABLED=false
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8001/health" ]
      interval: 10s
      timeout: 30s
      retries: 10
      start_period: 60s
    restart: on-failure

  frontend:
    container_name: airweave-frontend
    image: ${FRONTEND_IMAGE:-ghcr.io/airweave-ai/airweave-frontend:latest}
    ports:
      - "8082:8080"  # Port değiştirildi (8080 -> 8082)
    environment:
      - API_URL=http://localhost:8001
      - ENABLE_AUTH=false
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8080" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: on-failure

  text2vec-transformers:
    container_name: airweave-embeddings
    image: semitechnologies/transformers-inference:sentence-transformers-all-MiniLM-L6-v2
    ports:
      - "9879:8080"  # Port değiştirildi (9878 -> 9879)
    environment:
      ENABLE_CUDA: 0
      WORKERS_PER_NODE: 1
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: on-failure

  temporal:
    container_name: airweave-temporal
    image: temporalio/auto-setup:1.24.2
    ports:
      - "7233:7233"
      - "8233:8233"
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=supabase_admin
      - POSTGRES_PWD=PZQEkh2IrpL2CIo00gyuOzqdqnEwMT5I
      - POSTGRES_SEEDS=supabase-db-d0cso0goco0swwcgc4gkgw8c
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    healthcheck:
      test: [ "CMD", "tctl", "--address", "temporal:7233", "workflow", "list" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure

  temporal-ui:
    container_name: airweave-temporal-ui
    image: temporalio/ui:2.26.2
    ports:
      - "8088:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    depends_on:
      temporal:
        condition: service_healthy
    restart: on-failure

  temporal-worker:
    container_name: airweave-temporal-worker
    image: ${BACKEND_IMAGE:-ghcr.io/airweave-ai/airweave-backend:latest}
    environment:
      # Supabase PostgreSQL
      - POSTGRES_HOST=supabase-db-d0cso0goco0swwcgc4gkgw8c
      - POSTGRES_PORT=5432
      - POSTGRES_USER=supabase_admin
      - POSTGRES_PASSWORD=PZQEkh2IrpL2CIo00gyuOzqdqnEwMT5I
      - POSTGRES_DB=postgres
      
      # Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      
      # Qdrant
      - QDRANT_HOST=qdrant-ik4c0s48cwco4occo4kw8okg
      - QDRANT_PORT=6333
      
      # Text2Vec
      - TEXT2VEC_INFERENCE_URL=http://text2vec-transformers:8080
      
      # Environment
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - LOCAL_DEVELOPMENT=false
      
      # Temporal
      - TEMPORAL_HOST=temporal
      - TEMPORAL_PORT=7233
      - TEMPORAL_NAMESPACE=default
      - TEMPORAL_TASK_QUEUE=airweave-sync-queue
      - TEMPORAL_ENABLED=true
    entrypoint: [ "python", "-m", "airweave.platform.temporal.worker" ]
    depends_on:
      temporal:
        condition: service_healthy
    restart: on-failure

volumes:
  redis_data:
